// Extract the real approach video into a sequence of WebP frames for a
// canvas-based scroll scrub (smooth on ALL devices, unlike <video>.currentTime
// seeking which is throttled on mobile).
//
// Writes frames to website/public/frames/ and a manifest to
// website/src/lib/frames-manifest.js. Re-encode/crop only — no reinvention.
//
// Usage: node scripts/extract-frames.mjs [fps] [quality]
//   fps     : frames to extract per second (default: 18 -> ~145 frames). "max" = every frame.
//   quality : libwebp quality 0-100 (default: 72)
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import ffmpegPath from "ffmpeg-static";

const input = path.resolve("assets/references/mairie-dunkerque-approach-reference.mp4");
const outDir = path.resolve("website/public/frames");
const manifestPath = path.resolve("website/src/lib/frames-manifest.js");
const fpsArg = process.argv[2] || "18";
const quality = process.argv[3] || "72";

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

const vf =
  fpsArg === "max"
    ? "scale=1280:720:flags=lanczos"
    : `fps=${fpsArg},scale=1280:720:flags=lanczos`;

execFileSync(
  ffmpegPath,
  [
    "-y", "-i", input,
    "-vf", vf,
    "-c:v", "libwebp",
    "-quality", quality,
    "-compression_level", "6",
    "-vsync", "0",
    path.join(outDir, "frame-%03d.webp"),
  ],
  { stdio: "inherit" },
);

const files = fs.readdirSync(outDir).filter((f) => f.endsWith(".webp")).sort();
const total = files.reduce((s, f) => s + fs.statSync(path.join(outDir, f)).size, 0);

const manifest = `// AUTO-GENERATED by scripts/extract-frames.mjs — do not edit by hand.
export const FRAME_COUNT = ${files.length};
export const FRAME_PAD = 3;
export const FRAME_EXT = "webp";
export const FRAME_DIR = "frames";
`;
fs.writeFileSync(manifestPath, manifest);

console.log(
  `frames: ${files.length} | total: ${(total / 1048576).toFixed(2)} MB | ` +
    `avg: ${(total / files.length / 1024).toFixed(1)} KB | ${files[0]}..${files[files.length - 1]}`,
);
console.log("manifest ->", manifestPath);
